TOPDIR = ../..
include $(TOPDIR)/config.mk

SUBDIRS = common libxbps xbps-alternatives xbps-checkvers xbps-create xbps-install xbps-query xbps-rindex xbps-uhelper xbps-remove

include $(TOPDIR)/mk/subdir.mk
