-include ../../config.mk

SUBDIRS = common libxbps xbps-alternatives xbps-checkvers xbps-create xbps-digest xbps-install xbps-query xbps-rindex xbps-uhelper xbps-remove xbps-repodb

include ../../mk/subdir.mk
