-include ../../config.mk

SUBDIRS = common

SUBDIRS += cmpver
SUBDIRS += pkgpattern_match
SUBDIRS += plist_match
SUBDIRS += plist_match_virtual
SUBDIRS += util
SUBDIRS += find_pkg_obsoletes
SUBDIRS += pkgdb

include ../../mk/subdir.mk
