-include ../../config.mk

SUBDIRS = common

SUBDIRS += cmpver
SUBDIRS += pkgpattern_match
SUBDIRS += plist_array_replace
SUBDIRS += plist_find_array
SUBDIRS += plist_find_dictionary
SUBDIRS += plist_match
SUBDIRS += plist_match_virtual
SUBDIRS += plist_remove
SUBDIRS += util
SUBDIRS += find_pkg

include ../../mk/subdir.mk
