TOPDIR = ../../../..
include $(TOPDIR)/config.mk

TESTSSUBDIR = xbps/libxbps/config
TEST = config_test
EXTRA_FILES = Kyuafile xbps.cf xbps_nomatch.cf 1.include.cf 2.include.cf

include $(TOPDIR)/mk/test.mk
