TOPDIR = ../../../..
-include $(TOPDIR)/config.mk

TESTSSUBDIR = xbps/libxbps/config
TEST = config_test
EXTRA_FILES = Kyuafile xbps.conf xbps_nomatch.conf 1.include.conf 2.include.conf

include $(TOPDIR)/mk/test.mk
