TOPDIR = ../../../..
-include $(TOPDIR)/config.mk

TESTSHELL = conf_files_test issue6_test issue18_test issue20_test remove_test
TESTSHELL+= replace_test

include ../Makefile.inc
include $(TOPDIR)/mk/test.mk
