TOPDIR = ../../../..
-include $(TOPDIR)/config.mk

TESTSHELL = conf_files_test issue6_test issue18_test issue20_test remove_test
TESTSHELL+= replace_test installmode_test obsoletefiles_test
TESTSHELL+= issue31_test scripts_test incorrect_deps_test
TESTSHELL+= vpkg_test install_test preserve_files_test
TESTSHELL+= update_shlibs

include ../Makefile.inc
include $(TOPDIR)/mk/test.mk
