-include ../../../config.mk

SUBDIRS = common

SUBDIRS += cmpver
SUBDIRS += pkgpattern_match
SUBDIRS += plist_match
SUBDIRS += plist_match_virtual
SUBDIRS += util
SUBDIRS += find_pkg_obsoletes
SUBDIRS += find_pkg_orphans
SUBDIRS += pkgdb
SUBDIRS += issue6
SUBDIRS += issue18
SUBDIRS += issue20
SUBDIRS += conf_files

include ../../../mk/subdir.mk
