-include ../../../config.mk

SUBDIRS = common

SUBDIRS += cmpver
SUBDIRS += pkgpattern_match
SUBDIRS += plist_match
SUBDIRS += plist_match_virtual
SUBDIRS += util
SUBDIRS += util_path
SUBDIRS += find_pkg_orphans
SUBDIRS += pkgdb
SUBDIRS += config
SUBDIRS += shell

include ../../../mk/subdir.mk
